/* tslint:disable */
/* eslint-disable */
/**
 * Mythos Sandbox API 🏛️
 * Интерактивная песочница для работы с мифологией Древней Греции.  **Base URL:** `https://api.qasandbox.ru/api`  ---  * **Обучение:** Освоить работу всех методов песочницы в Postman можно [на этом курсе](https://stepik.org/a/269008).  ---  ### 🛠 Особенности реализации:  * **Auth:** Методы изменения (**POST**, **PUT**, **PATCH**, **DELETE**) требуют JWT-токен в заголовке `Authorization`.  * **System Lock:** Персонажи с **ID 1–31** защищены. При попытке изменения сервер вернет ошибку `403 Forbidden`.  * **Data Mapping:** В API используется поле `desc`.     * В базе данных оно хранится как `description`.  * **Localization (EN):** В параметрах и поле `category` используются английские значения:      `gods`, `heroes`, `creatures`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface LoginPost200Response {
    'token'?: string;
}
export interface LoginPostRequest {
    'username'?: string;
    'password'?: string;
}
export interface ModelError {
    'error'?: string;
}
export interface MythologyEntity {
    'id'?: number;
    'name': string;
    'category': MythologyEntityCategoryEnum;
    /**
     * Содержимое колонки description в БД
     */
    'desc': string;
    'img'?: string;
}

export const MythologyEntityCategoryEnum = {
    Gods: 'gods',
    Heroes: 'heroes',
    Creatures: 'creatures'
} as const;

export type MythologyEntityCategoryEnum = typeof MythologyEntityCategoryEnum[keyof typeof MythologyEntityCategoryEnum];

export interface MythologyIdPatchRequest {
    'name'?: string;
    'desc'?: string;
    'category'?: MythologyIdPatchRequestCategoryEnum;
    'img'?: string;
}

export const MythologyIdPatchRequestCategoryEnum = {
    Gods: 'gods',
    Heroes: 'heroes',
    Creatures: 'creatures'
} as const;

export type MythologyIdPatchRequestCategoryEnum = typeof MythologyIdPatchRequestCategoryEnum[keyof typeof MythologyIdPatchRequestCategoryEnum];

export interface RegisterPostRequest {
    'username': string;
    'password': string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Вход и получение токена
         * @param {LoginPostRequest} loginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginPost: async (loginPostRequest: LoginPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginPostRequest' is not null or undefined
            assertParamExists('loginPost', 'loginPostRequest', loginPostRequest)
            const localVarPath = `/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Регистрация нового пользователя
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost: async (registerPostRequest: RegisterPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerPostRequest' is not null or undefined
            assertParamExists('registerPost', 'registerPostRequest', registerPostRequest)
            const localVarPath = `/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Вход и получение токена
         * @param {LoginPostRequest} loginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginPost(loginPostRequest: LoginPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginPost(loginPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Регистрация нового пользователя
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerPost(registerPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.registerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Вход и получение токена
         * @param {LoginPostRequest} loginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginPost(loginPostRequest: LoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginPost200Response> {
            return localVarFp.loginPost(loginPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Регистрация нового пользователя
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.registerPost(registerPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Вход и получение токена
     * @param {LoginPostRequest} loginPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public loginPost(loginPostRequest: LoginPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginPost(loginPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Регистрация нового пользователя
     * @param {RegisterPostRequest} registerPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerPost(registerPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EntitiesApi - axios parameter creator
 */
export const EntitiesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получить список всех сущностей
         * @param {MythologyGetCategoryEnum} [category] Фильтрация по категории. Используйте \&#39;all\&#39; для всех.
         * @param {MythologyGetSortEnum} [sort] Сортировка по имени (asc — А-Я, desc — Я-А)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyGet: async (category?: MythologyGetCategoryEnum, sort?: MythologyGetSortEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mythology`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Изгнать сущность (удаление)
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('mythologyIdDelete', 'id', id)
            const localVarPath = `/mythology/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Частичное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyIdPatchRequest} [mythologyIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdPatch: async (id: number, mythologyIdPatchRequest?: MythologyIdPatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('mythologyIdPatch', 'id', id)
            const localVarPath = `/mythology/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mythologyIdPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Полное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdPut: async (id: number, mythologyEntity: MythologyEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('mythologyIdPut', 'id', id)
            // verify required parameter 'mythologyEntity' is not null or undefined
            assertParamExists('mythologyIdPut', 'mythologyEntity', mythologyEntity)
            const localVarPath = `/mythology/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mythologyEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Призвать новую сущность
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyPost: async (mythologyEntity: MythologyEntity, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mythologyEntity' is not null or undefined
            assertParamExists('mythologyPost', 'mythologyEntity', mythologyEntity)
            const localVarPath = `/mythology`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mythologyEntity, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EntitiesApi - functional programming interface
 */
export const EntitiesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EntitiesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получить список всех сущностей
         * @param {MythologyGetCategoryEnum} [category] Фильтрация по категории. Используйте \&#39;all\&#39; для всех.
         * @param {MythologyGetSortEnum} [sort] Сортировка по имени (asc — А-Я, desc — Я-А)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mythologyGet(category?: MythologyGetCategoryEnum, sort?: MythologyGetSortEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MythologyEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mythologyGet(category, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntitiesApi.mythologyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Изгнать сущность (удаление)
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mythologyIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mythologyIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntitiesApi.mythologyIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Частичное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyIdPatchRequest} [mythologyIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mythologyIdPatch(id: number, mythologyIdPatchRequest?: MythologyIdPatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MythologyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mythologyIdPatch(id, mythologyIdPatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntitiesApi.mythologyIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Полное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mythologyIdPut(id: number, mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MythologyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mythologyIdPut(id, mythologyEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntitiesApi.mythologyIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Призвать новую сущность
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mythologyPost(mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MythologyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mythologyPost(mythologyEntity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntitiesApi.mythologyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EntitiesApi - factory interface
 */
export const EntitiesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EntitiesApiFp(configuration)
    return {
        /**
         * 
         * @summary Получить список всех сущностей
         * @param {MythologyGetCategoryEnum} [category] Фильтрация по категории. Используйте \&#39;all\&#39; для всех.
         * @param {MythologyGetSortEnum} [sort] Сортировка по имени (asc — А-Я, desc — Я-А)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyGet(category?: MythologyGetCategoryEnum, sort?: MythologyGetSortEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<MythologyEntity>> {
            return localVarFp.mythologyGet(category, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Изгнать сущность (удаление)
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.mythologyIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Частичное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyIdPatchRequest} [mythologyIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdPatch(id: number, mythologyIdPatchRequest?: MythologyIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<MythologyEntity> {
            return localVarFp.mythologyIdPatch(id, mythologyIdPatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Полное обновление сущности
         * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyIdPut(id: number, mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig): AxiosPromise<MythologyEntity> {
            return localVarFp.mythologyIdPut(id, mythologyEntity, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Призвать новую сущность
         * @param {MythologyEntity} mythologyEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mythologyPost(mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig): AxiosPromise<MythologyEntity> {
            return localVarFp.mythologyPost(mythologyEntity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EntitiesApi - object-oriented interface
 */
export class EntitiesApi extends BaseAPI {
    /**
     * 
     * @summary Получить список всех сущностей
     * @param {MythologyGetCategoryEnum} [category] Фильтрация по категории. Используйте \&#39;all\&#39; для всех.
     * @param {MythologyGetSortEnum} [sort] Сортировка по имени (asc — А-Я, desc — Я-А)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mythologyGet(category?: MythologyGetCategoryEnum, sort?: MythologyGetSortEnum, options?: RawAxiosRequestConfig) {
        return EntitiesApiFp(this.configuration).mythologyGet(category, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Изгнать сущность (удаление)
     * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mythologyIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return EntitiesApiFp(this.configuration).mythologyIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Частичное обновление сущности
     * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
     * @param {MythologyIdPatchRequest} [mythologyIdPatchRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mythologyIdPatch(id: number, mythologyIdPatchRequest?: MythologyIdPatchRequest, options?: RawAxiosRequestConfig) {
        return EntitiesApiFp(this.configuration).mythologyIdPatch(id, mythologyIdPatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Полное обновление сущности
     * @param {number} id ID сущности (Внимание! ID 1-31 защищены от правок)
     * @param {MythologyEntity} mythologyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mythologyIdPut(id: number, mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig) {
        return EntitiesApiFp(this.configuration).mythologyIdPut(id, mythologyEntity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Призвать новую сущность
     * @param {MythologyEntity} mythologyEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mythologyPost(mythologyEntity: MythologyEntity, options?: RawAxiosRequestConfig) {
        return EntitiesApiFp(this.configuration).mythologyPost(mythologyEntity, options).then((request) => request(this.axios, this.basePath));
    }
}

export const MythologyGetCategoryEnum = {
    All: 'all',
    Gods: 'gods',
    Heroes: 'heroes',
    Creatures: 'creatures'
} as const;
export type MythologyGetCategoryEnum = typeof MythologyGetCategoryEnum[keyof typeof MythologyGetCategoryEnum];
export const MythologyGetSortEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type MythologyGetSortEnum = typeof MythologyGetSortEnum[keyof typeof MythologyGetSortEnum];


