/* tslint:disable */
/* eslint-disable */
/**
 * Mythos Sandbox API 🏛️
 * Интерактивная песочница для работы с мифологией Древней Греции.  **Base URL:** `https://api.qasandbox.ru/api`  ---  * **Обучение:** Освоить работу всех методов песочницы в Postman можно [на этом курсе](https://stepik.org/a/269008).  ---  ### 🛠 Особенности реализации:  * **Auth:** Методы изменения (**POST**, **PUT**, **PATCH**, **DELETE**) требуют JWT-токен в заголовке `Authorization`.  * **System Lock:** Персонажи с **ID 1–31** защищены. При попытке изменения сервер вернет ошибку `403 Forbidden`.  * **Data Mapping:** В API используется поле `desc`.     * В базе данных оно хранится как `description`.  * **Localization (EN):** В параметрах и поле `category` используются английские значения:      `gods`, `heroes`, `creatures`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "https://api.qasandbox.ru/api".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {
}
