/* tslint:disable */

/**
 * Mythos Sandbox API 🏛️
 * Интерактивная песочница для работы с мифологией Древней Греции.  **Base URL:** `https://api.qasandbox.ru/api`  ---  * **Обучение:** Освоить работу всех методов песочницы в Postman можно [на этом курсе](https://stepik.org/a/269008).  ---  ### 🛠 Особенности реализации:  * **Auth:** Методы изменения (**POST**, **PUT**, **PATCH**, **DELETE**) требуют JWT-токен в заголовке `Authorization`.  * **System Lock:** Персонажи с **ID 1–31** защищены. При попытке изменения сервер вернет ошибку `403 Forbidden`.  * **Data Mapping:** В API используется поле `desc`.     * В базе данных оно хранится как `description`.  * **Localization (EN):** В параметрах и поле `category` используются английские значения:      `gods`, `heroes`, `creatures`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
